#!/system/bin/sh

mount -o remount,rw /system

ln -s /persist/WCNSS_qcom_wlan_factory_nv.bin /system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_factory_nv.bin
ln -s /system/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini  /system/etc/wifi/WCNSS_qcom_cfg.ini

mount -o remount,ro /system

